// <auto-generated />
namespace Lesson1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Resort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resort));
        
        string IMigrationMetadata.Id
        {
            get { return "202301210204173_Resort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
